name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4.1.5

     - name: Set up JDK
       uses: actions/setup-java@v4.2.1
   
     - name: Build with Gradle
       run: ./gradlew build
    
